### ISSUE TITLE
La app Electron no muestra el ícono de Pilas Bloques en la taskbar (Linux)

### ISSUE THREAD

**Issue by asanzo** [Program-AR/pilas-bloques-app#168]
![Selección_999(246)](https://user-images.githubusercontent.com/5421992/63804669-0c8f4b80-c8ee-11e9-95bb-44b3b3582af7.png)

Con el instalador .deb ni con el portable.

**Comment by rgonzalezt** [comment]
Se encara en https://github.com/Program-AR/pilas-bloques-app/issues/173
