### ISSUE TITLE
Vite: Meter un framework a React 

### ISSUE THREAD

**Issue by tfloxolodeiro** [Program-AR/pilas-bloques-app#205]
La pagina de [crear un nuevo proyecto de React](https://react.dev/learn/start-a-new-react-project) dice que si queres crear un nuevo proyecto de react deberias usar un framework. Hay una [justificacion](https://react.dev/learn/start-a-new-react-project#can-i-use-react-without-a-framework) con unas vibras un poco pasivo agresivas de por que realmente no queres usar react sin un framework.

Habria que ver cual de los frameworks que hay nos convendria mas para justificar meter un framework a react.

Por otra parte, create-react-app está deprecado asi que esto cuenta como deuda tecnica.

**Comment by asanzo** [comment]
Me crucé con esto intentando arreglar tests:
https://www.freecodecamp.org/news/how-to-migrate-from-create-react-app-to-vite/

**Comment by danielferro69** [comment]
> Me crucé con esto intentando arreglar tests: https://www.freecodecamp.org/news/how-to-migrate-from-create-react-app-to-vite/

Estuve leyendo la migracion. Interesante y a la vista, simple. Si lo desean (te quedan apenas unas horas para decidirlo) intento hacer la migracion a Vite con los pasos indicados en el doc para ver si nos topamos con alguna dificultad, lo tiramos a un PR y como dice el final del paper, quiza podamos decir **_Voilà! You're done and your application is fully migrated._**
