### ISSUE TITLE
Blockly - Hacer el toolbox mas bonito

### ISSUE THREAD

**Issue by tfloxolodeiro** [Program-AR/pilas-bloques-app#219]
Ahora está metido asi nomas al lado de la seleccion de bloques 

- [x] Agregar un título "Previsualización" o "Así se verá tu caja de herramientas"
- [x] quizás meterlo en una PBCard para que se entienda que es una preview, como con el enunciado.

![image](https://github.com/Program-AR/pilas-bloques-react/assets/37090248/e218b721-840e-455c-912b-1a44e5e27702)

**Comment by rgonzalezt** [comment]
Hecho en https://github.com/Program-AR/pilas-bloques-app/pull/239
