### ISSUE TITLE
Las latas de Capy se hacen gigantes

### ISSUE THREAD

**Issue by rgonzalezt** [Program-AR/pilas-bloques-app#232]
En el ejercicio [1042](https://pilasbloques.program.ar/online/#/desafio/1042) las latas empiezan a "crecer" cuando se las recoge.
Según estuvo investigando @dlopezalvas, al parecer está relacionado con el mapa, específicamente con las casillas vacías.

 [Acá](https://drive.google.com/drive/folders/1g1nbZNEalcjZPfhw5E5-FD2tiLx17tNQ) se encuentra un video mostrando como se comportan las latas y la solución que se ve en el mismo.

**Comment by dlopezalvas** [comment]
Ya está releaseado todo y actualizado en este repo :+1:
