### ISSUE TITLE
Bloques: Traerse el código que escupe cada bloque

### ISSUE THREAD

**Issue by asanzo** [Program-AR/pilas-bloques-app#250]
Depende de (o se hace con) #248 

El objetivo de este issue es conseguir en React que funcione un método similar a [`javascriptcode()`](https://github.com/Program-AR/pilas-bloques-ember/blob/develop/app/components/pilas-blockly.js) de ember.

https://github.com/Program-AR/pilas-bloques-ember/blob/c8ddf9bc9eb0606515fd6ea45209461fa42624a5/app/components/pilas-blockly.js#L461-L465

- [ ] Tests unitarios: Cada bloque debería poder escupir el código que le corresponde.
- [ ] Test de integración: el javascriptCode debería escupir el programa con los highlights
- [ ] Copiar tests de ember!!!

**Comment by danielferro69** [comment]
@dlopezalvas @rgonzalezt 

Como Blockly es ahora un poco distinto con el tema del codigo, quiza esta customizacion que hizo un usuario de react-blockly pueda servirnos para transformar el codigo.

https://github.com/FernandoVazZ/reactblockly-customblocks/blob/main/src/customBlocks/custom_Blocks.js

Entiendo que quiza, como hace este usuario llevando cada bloque a Python, podamos hacer lo mismo con JavaScript. 
Sin haber visto mas que este codigo y no haber analizado en detalle el propio en ember, pero si estuve viendo que cambia la forma de construccion.
