### ISSUE TITLE
QUEJA HACIA PILAS BLOQUES

### ISSUE THREAD

**Issue by emiriosvit** [Program-AR/pilas-bloques-app#273]
Este juego es un fraude. No he logrado completar ningun nivel, y no fue mi culpa, hay demasiados errores, ademas la pagina es terrible, media hora en cargar, porfavor, ocupense de sus problemas, GRACIAS.

**Comment by rgonzalezt** [comment]
¡Hola! ¿Cómo estás? Gracias por tu devolución. Lamentamos mucho que la página cargue lento, estamos trabajando en ello y próximamente lo solucionaremos. ¿Por qué no podés resolver un nivel? Contanos más así podemos resolver tu inquietud.

¡Saludos!
El equipo de Pilas Bloques
