### ISSUE TITLE
Bugs varios

### ISSUE THREAD

**Issue by rgonzalezt** [Program-AR/pilas-bloques-app#290]
Antes de salir a producción con la nueva pantalla desafío en el creador tenemos que:

- [x] Sacar la categoría variables del toolbox (tanto del selector del creador como del toolbox del desafio).
- [x] Revisar las primitivas que aparecen (hay varias que no deberían ir como "Avanzar", "Escribir", "Saltar", etc).
- [x] Revisar si el toolbox selector se puede usar bien en modo vertical. No me molestaría que salga con una ux no tan buena pero sí que se pueda usar.

**Comment by danielferro69** [comment]
@rgonzalezt 

Preguntas:
El 1er punto ya esta en el PR #293 igual lo dejo aca tambien.
Lo de las primitivas, ok
Ahora el ultimo punto no entedí bien qué habria que hacer...
Mas alla de que en la version del PR #293 ya hace que las categorias solo se muestren las que tienen bloques
Vos decis de hacer algo asi ??? es decir, que el toolbox sea scrollable como cada categoria de bloques ?

https://github.com/Program-AR/pilas-bloques-app/assets/91342656/2b9634fe-6b9a-45c8-a114-1a4daaff57c4

Porque si es esto, ya subo esto hecho a un PR nuevo

sino es esto, contame.

**Comment by danielferro69** [comment]
@rgonzalezt 


https://github.com/Program-AR/pilas-bloques-app/assets/91342656/700e3445-2ceb-4eaf-8d5f-e5a44ac32390

**Comment by danielferro69** [comment]
@rgonzalezt 

https://github.com/Program-AR/pilas-bloques-app/assets/91342656/ab7fd9f1-6217-463d-8455-2a04e2e272be
